### PR TITLE
fix: the agent answers restart requests with the owner's real path

### PR DESCRIPTION
**Pull request by KrasimirKralev**
**TASK-612 (decision D-08)** — "Restart the gateway" from chat, answered instead of queued.

## Symptom

Asked in chat to restart the gateway, the OpenClaw agent queued an operator-approval proposal and told the owner the restart was waiting for their approval. ClawBox renders no approval card anywhere, so the proposal was shown to nobody: it waited until the run ended, or until the very restart it asked for cancelled it (`operator_approval_cancelled_gateway_restart`). The chat even connects with the `operator.approvals` scope (`ChatApp.tsx`, `ChatPopup.tsx`, `clientId: openclaw-control-ui`), so the gateway happily routes an `approval.request` to a client that handles none — which is exactly why it parks.

## What the guide now says, and why the first draft of it was wrong

The agent was right about the mechanism and wrong about this device, so the fix is an instruction. The first draft of that instruction said *"you have no tool for any of them"* — which is false and would have been worse than the bug: `mcp/tools/system.ts` registers **`system_power`** (restart/shutdown, `confirm: true`, `reason`) on **both** editions, `config/clawbox-sudoers` grants `NOPASSWD: systemctl restart clawbox-gateway.service`, and `Clawbox.md` (the Field Guide the orientation tool loads on both editions) documents `system_power` as reboot/shutdown. A guide that contradicts the Field Guide in the same context window makes behaviour less deterministic, not more. It also sent the owner to Settings → System for a restart; that tab is the harness picker, the performance mode, read-only stats and the password — **no power control at all** (`SettingsApp.tsx`).

So the section, corrected:

- a **gateway** restart is not the agent's to do from a chat turn — the gateway hosts the session, so the restart kills the reply before it lands — and it is rarely needed, because a setting that requires one restarts it on save (Settings → Providers, Voice, Channels);
- a **device** restart or shutdown **is** the agent's, via `system_power` with `confirm: true`, when the owner asked in their own words; the owner's own control is the **tray power menu**; Settings → About holds the update, and the device name is the Local URL card under Settings → Network (round 2 corrected this — see H1 below);
- an `operator_approval` proposal must **never** be queued — and a parked one is answered with `openclaw approvals pending` / `openclaw approvals resolve <id> allow-once|allow-always|deny` from the Terminal app, which is a truer and more useful sentence than "there is nowhere to approve it".

## Native mechanism (harness-first) — and where it decided the design

Operator approvals are OpenClaw's, entirely; this PR builds no part of them. Verified in the pinned core (2026.8.1 per `config/openclaw-target.txt`, read-only on the box): `approval.request` / `approval.get` / `approval.resolve` / `approval.history` behind the `operator.approvals` scope, the `openclaw approvals` CLI, `openclaw exec-policy` for approval policy, and `approvals.exec.*` / `approvals.plugin.*` in config. Rendering a pending approval as an approve/deny card on that RPC is **TASK-704** under TASK-604, post-v4; that task names this paragraph as the thing to revise when it lands. A policy-level answer (`openclaw exec-policy set --ask …`) was considered and not taken here: `exec-policy` governs *exec* approvals, and it is not established that the TASK-612 proposal was one — that is TASK-704's question, not a one-liner.

The harness also decided **where the rule lives**. OpenClaw's workspace file map (`docs/concepts/agent-workspace.md`, read from the installed package) injects `AGENTS.md`, `SOUL.md`, `USER.md`, `IDENTITY.md`, `BOOT.md`, `BOOTSTRAP.md` and `memory/` at the start of every session, and describes `AGENTS.md` as *"operating instructions … good place for rules"*. **`CLAWBOX.md` is not in that set** — it is read only if the agent chooses to open it, prompted by one pointer sentence. Shipping a behavioural prohibition only there would have been green tests over a rule the model may never load.

So the rule itself is appended to **`AGENTS.md`**, under a marker of its own — deliberately not the existing `"CLAWBOX.md"` marker, which is already present on every box in the field (verified: the dev box's `AGENTS.md` still carries the original pointer sentence) and can therefore never deliver anything again. `CLAWBOX.md` keeps the long form.

## The delivery half

`gateway-pre-start.sh` seeds `CLAWBOX.md` **if missing**, deliberately, so an owner's or the agent's edits are never clobbered. The cost had never been measured: the dev box's `CLAWBOX.md` is dated **Aug 13 with five headings** and has therefore never received `## Coding agent` either — a whole section about `coding_agent_run` that no field box has. An existing guide is now topped up with the one missing section: appended, never overwritten, keyed on its heading so a second start appends nothing, with the text lifted from the template by awk so there is one source. Generalising that to every missing section is a policy call (an owner may have deleted a section on purpose) and is filed as **TASK-706** with the measurement.

All three appends are failure-tolerant with an honest warning, because pre-start runs under `set -euo pipefail` and these files are advisory. That included fixing a pre-existing hazard my own test caught: the `AGENTS.md` pointer append has always been bare, so a read-only `AGENTS.md` aborted pre-start and **left the gateway down over a pointer sentence**.

## RED → GREEN

RED, guide content, on unmodified `origin/beta`:

```
FAIL src/tests/unit/clawbox-workspace-guide.test.ts (4 tests | 4 failed)
  × carries a section on system actions and restarts
      AssertionError: expected '' to match /^## .*System actions/
  × separates the gateway restart it refuses from the device restart it owns
      AssertionError: expected '' to contain 'gateway'
  × names controls that exist: the tray power menu, and Settings -> System for what is there
      AssertionError: expected '' to match /power menu/i
  × forbids queueing an operator-approval proposal, and names the way to answer a parked one
      AssertionError: expected '' to contain 'operator_approval'
```

RED, delivery — beta's `gateway-pre-start.sh` against the NEW template, i.e. exactly what a guide-only fix would have shipped (11 of 14 fail):

```
FAIL src/tests/unit/gateway-pre-start-workspace-guide.test.ts (14 tests | 11 failed)
  × appends the system-actions section to a guide written before it existed
      AssertionError: expected '' to contain 'Appended the system-actions section'
  × appends once, however many times the gateway starts
      AssertionError: expected [ Array(1) ] to have a length of 2 but got 1
  × takes only that section, not the ones that follow it in the template
  × warns instead of appending an empty section when the template loses the heading
  × warns and lets the gateway start when the guide cannot be written
      AssertionError: expected '' to contain 'could not append'
  × keeps the appended section as its own heading when the guide has no trailing newline
  × appends the section at the end, after whatever the owner already had
  × appends the rule to an AGENTS.md that already carries the old pointer
      AssertionError: expected '' to contain 'Appended the system-actions rule to AGENTS.md'
  × appends the rule once, however many times the gateway starts
  × names system actions in the pointer it appends to a fresh AGENTS.md
  × does not stop the gateway when AGENTS.md cannot be written
```

(The pre-start tests bound the shipped block with an `# --- end guide seeding ---` sentinel so they cannot execute whatever is appended to the script next; beta's copy was given that comment line, and nothing else, to run them against it.)

GREEN on this branch: both files 18/18, full suite 663 files / 9592 tests. `tsc --noEmit` clean, eslint clean on the new files. Two other full-suite runs on this same head each showed a *different* component-test flake under parallel load (`app-store-errors` → `obs.observe is not a function`; `chat-spoken-reply` → a 6.2 s timeout); both pass in isolation, both are pre-existing, and this diff contains no component or runtime TypeScript at all.

## Siblings

- `gateway-pre-start.sh` is the only writer of `CLAWBOX.md` in the repo; `install.sh` does not touch it.
- The `AGENTS.md` pointer sentence now names system actions as a topic, so a box that has not yet been given the pointer gets an accurate one.
- `Clawbox.md` (Field Guide) and `mcp/README.md` describe `system_power` as reboot/shutdown; after the correction above the three agent-facing sources agree, so neither needed an edit.
- **No Hermes leg.** `scripts/setup-hermes-edition.sh` stops, disables, removes and masks `clawbox-gateway.service`, so `gateway-pre-start.sh` never runs and neither file is written on the Hermes SKU; and the Hermes chat path auto-answers approvals (`hermes-dashboard-turn.ts`, `APPROVAL_CHOICE = "once"`), so a parked proposal cannot reproduce there. On the dual SKU the OpenClaw gateway unit is not masked, so this seeds normally and applies to the OpenClaw agent — correct as-is.

## Review

One Opus review pass: 3 high, 4 medium, 8 low. All three high findings were real and are fixed above (the false "no tool" claim, the wrong Settings path, and the rule shipping in a file the harness never injects); the low findings on the shell block (awk terminated on `---` rather than the next heading, an I/O failure misreported as a renamed heading, a missing trailing-newline guard producing a setext heading, a `2>/dev/null` that suppressed nothing, a root-invisible test skip, an unbounded block slice) are all applied. Two medium findings are filed rather than folded in: generalising the top-up (**TASK-706**) and the approvals card (**TASK-704**).

## Follow-ups filed

- **TASK-704** — render `operator_approvals` as an approve/deny chat card on the native approvals RPC (post-v4).
- **TASK-706** — `CLAWBOX.md` is frozen at the sections a box was seeded with; the `## Coding agent` section has never reached a field box.

## Summary by CodeRabbit

- **Documentation**
  - Added guidance for safe system restarts, supported device power actions, and restrictions on restarting the gateway from chat.
  - Clarified system settings locations and how to resolve parked approval requests through the Terminal app.
  - Added guidance prohibiting approval proposals from chat when no approval card is available.

- **Reliability**
  - Workspace guidance updates now preserve existing content and avoid interrupting startup when optional files cannot be read or written.
  - Repeated setup runs avoid duplicating guidance.

## Round 2 — the Opus final review BLOCKED `5017bc85`; this is the response

Two HIGH findings, one MEDIUM, and the LOWs. Commit `d1d74fca`.

### H1 (blocking) — the guide named the wrong Settings screen for the device name

`config/clawbox-workspace-guide.md` said *"the update and the hostname (which reboots on save) are
under Settings → About."* Half of that was false, and it is the identical wrong-screen defect this
section exists to remove — one clause later, shipping to every box through the top-up.

Measured at this head:

- The **editable** device name is the `{/* Local URL (mDNS hostname) card */}` at
  `SettingsApp.tsx:3425`, inside `{activeSection === "wifi" && (` (`:3241–3631`). That nav entry is
  `{ id: "wifi", icon: "wifi", labelKey: "settings.network" }` (`:255`), and
  `"settings.network": "Network"` (`src/lib/translations.ts:302`). The owner sees
  **Settings → Network**. Saving it POSTs `/setup-api/system/power` (`:1090`) — hence "reboots".
- **Settings → About** (`{activeSection === "about" && (`, `:5638`) holds the version card, the
  docs/support/Discord links, the Beta toggle, the System Update tile (`:5746–5759`) and Factory
  reset. Grepping `:5638–5800` for `hostname|rename|deviceName|Local URL` returns **nothing**.

Now: *"The update is under Settings → About. The device name is the Local URL card under
Settings → Network, and saving it reboots the box."* Pinned by a new test that fails if any clause
naming the device name stops naming Network or starts naming About.

### H2 (blocking, boot path) — the seed write was the one still bare under `set -euo pipefail`

`scripts/gateway-pre-start.sh` — the PR guarded the two appends and the pre-existing bare pointer
append, but `install -m 644` (the CLAWBOX.md seed) was still bare.
`config/clawbox-gateway.service:20` is `ExecStartPre=…/gateway-pre-start.sh` with **no leading `-`**,
so a non-zero exit fails the unit; with `Restart=always`, `RestartSec=5`,
`StartLimitBurst=20` / `StartLimitIntervalSec=3600` it burns twenty starts in ~100 s and then sits
failed for the rest of the hour. **The gateway is down over an advisory text file** — and the seed is
exactly the first-boot and post-factory-reset path. Reachable on a full rootfs (ENOSPC on a Jetson
eMMC), a filesystem remounted read-only after errors, an unreadable template, or the documented
"delete CLAWBOX.md to re-seed" step on such a box.

Guarded like the appends: warn on stderr, boot continues.

The template test also moves from `-f` to `-r` — `-f` waves an existing-but-unreadable template
through into a write that then fails. It is placed **inside** the CLAWBOX.md chain rather than in the
enclosing condition on purpose: the AGENTS.md rule below needs no template at all, and gating the
delivery leg of this fix on a file it does not read would have been a worse coupling than the one
being removed.

And the block comment that asserted an invariant which did not hold ("Both halves below can fail
without the gateway caring") is replaced by one that is true for **every** write in the block, stated
where it applies to all of them. It also carried a stale sentence about a `|| true` that no longer
exists in the code, and another claiming the awk "prints … to the `---` that closes the section",
which the previous round had already stopped being true. Both are gone.

### M1 — the pointer/rule ordering was load-bearing and silently coupled

The rule's body ends `` `CLAWBOX.md` has the long form. ``, so it satisfies the pointer block's
`! grep -qF "CLAWBOX.md"` guard. Both blocks landed only because the pointer is written first in the
file; any reorder — or moving the rule into a helper that ran earlier — would have cost every fresh
box its `## ClawBox integration` pointer forever, with both markers "satisfied", no warning, and the
suite still green.

Decoupled rather than documented: the guard is now `grep -qF "## ClawBox integration"`, hoisted into
`CLAWBOX_AGENTS_POINTER` so the literal has one source. This cannot double-append on a field box —
`git log -S'## ClawBox integration' -- scripts/gateway-pre-start.sh` returns exactly one commit
(`1f55a391`, where the pointer was introduced), so the heading every box carries is byte-identical to
the one being grepped. Pinned by a test that seeds an `AGENTS.md` carrying the rule (and therefore
the literal `CLAWBOX.md`) but not the heading, and requires the pointer to land anyway.

### M2 — `## Coding agent` backfill is **TASK-706**, not this PR

Only the new `## System actions and restarts` section is backfilled onto the Aug-13 `CLAWBOX.md` that
field boxes carry. That file is also missing `## Coding agent (delegate a whole task)` from the
shipped template, so the agent on those boxes still will not learn that `coding_agent_run` exists.
Generalising the top-up to every missing heading is a policy call (an owner may have deleted a
section deliberately) and is filed with its measurement as **TASK-706**. Not in scope here; the
AGENTS.md leg means TASK-612's rule lands regardless of CLAWBOX.md drift.

### LOW findings — applied or refuted

| # | Finding | Outcome |
|---|---|---|
| L1 | "Settings → AI" names a tab labelled "Providers" | **Applied.** `{ id: "ai", … labelKey: "settings.providers" }` (`SettingsApp.tsx:245`), `"settings.providers": "Providers"` (`src/lib/desktop-translations.ts:411`). Guide and the AGENTS.md rule now say **Settings → Providers**; Voice and Channels were already right. Pinned by a test. |
| L2 | A short write could leave a truncated section the marker then declares complete | **Refuted in round 2, then escalated by the round-3 pass with a working reproduction — now deferred and filed as TASK-707.** See "Deferred, with reasons" below. |
| L3 | The topped-up guide ended on a dangling `---` | **Applied.** The awk now drops trailing blank lines and a trailing rule (CR-tolerant, so a CRLF template is handled too). Verified: the file now ends `…leaving them waiting.` Pinned by a test. |
| L4 | Stale docstring teaching the reversed instruction | **Applied.** The docstring and the test title no longer name Settings → System as the owner's path. Also corrects the follow-up id to **TASK-704** (under TASK-604), per CodeRabbit's thread. |
| L5 | `awk -v heading=…` interprets escapes in the value | **Applied.** The heading is passed through the environment and read via `ENVIRON["heading"]`. |
| L6 | Nothing exercises a genuinely older CLAWBOX.md | **Acknowledged, not fixed.** A checked-in fixture would have to be copied off a field box; this PR touches no device, and the box's file is not in the repo. It is the same gap M2/TASK-706 records, and TASK-706 is where the real file gets captured. |

### Sibling call sites

- **Other unguarded writes in `gateway-pre-start.sh`** (the sweep H2 demands): `:2138`
  `mkdir -p "$(dirname "$MCP_TOKEN_FILE")"` and `:2149` `chmod 600 "$MCP_TOKEN_FILE"` are bare, and
  **deliberately left bare**. That file is the sole `/setup-api/*` bearer credential: a gateway that
  starts with a missing or world-readable bearer is worse than one that does not start, so failing
  the unit is the correct outcome there. The two `mkdir` calls at `:2119` and `:2312` are already
  `2>/dev/null || true`. No other write in the script opens a statement.
- **Other `ExecStartPre=`**: only `clawbox-gateway.service:20` lacks a leading `-`;
  `clawbox-hermes-dashboard.service` uses `ExecStartPre=-` on both of its hooks, so H2's failure mode
  is unique to this unit.
- **Other "Settings → About" references**: `scripts/force-update.sh:86` and `SystemUpdateApp.tsx:287`
  both name About for the **update**, which is correct. Nothing else sends anyone to About for a
  device name.
- **Out-of-scope finding, filed not fixed**: `mcp/README.md:140` ("one click in Settings → AI"),
  `src/lib/coding-agent.ts:1252`, `src/lib/coding-agent-mcp-refresh.ts:75`,
  `src/lib/hermes-clawai.ts:134` and `e2e/helpers/clawbox.ts:599` all say "Settings → AI Models" /
  "Settings → AI" in owner-facing text, and `src/tests/unit/mcp-tool-honesty.test.ts:767` pins
  "Settings -> AI Providers". Same class as L1, in files this PR does not own — flagged here rather
  than folded into the diff.

### RED → GREEN (round 2)

RED, at `5017bc85` with the new tests added and nothing else changed:

```
 ❯ src/tests/unit/clawbox-workspace-guide.test.ts (6 tests | 2 failed)
     × names the screen each control is actually on, not the one next to it
         AssertionError: expected '## System actions and restarts…' to match /Settings\s*→\s*Network/
     × names the restart-on-save tabs by their labels
         AssertionError: expected '## System actions and restarts…' to match /Settings\s*→\s*Providers/
 ❯ src/tests/unit/gateway-pre-start-workspace-guide.test.ts (17 tests | 4 failed)
     × warns and lets the gateway start when the workspace cannot be seeded
         AssertionError: expected 1 to be +0   ← the block exits 1; the unit fails
     × starts no statement in the seeding block with a bare copy, whatever the uid
         AssertionError: expected [ Array(1) ] to deeply equal []
     × takes only that section, not the ones that follow it in the template
         AssertionError: expected true to be false   ← trailing `---`
     × appends the pointer even when the rule already put the literal CLAWBOX.md in the file
         AssertionError: expected '' to contain 'Appended CLAWBOX.md reference to AGEN…'

 Test Files  2 failed (2)
      Tests  6 failed | 17 passed (23)
```

The H2 case reproduced directly out of the shipped `.sh` (block extracted between its sentinels and
run under `set -euo pipefail`), workspace `0555`, `CLAWBOX.md` absent — before and after:

```
=== PRE-FIX (5017bc85) ===
install: cannot create regular file '…/workspace/CLAWBOX.md': Permission denied
[exit=1]                  ← ExecStartPre fails; the unit fails; StartLimitBurst burns

=== POST-FIX (d1d74fca), identical conditions ===
install: cannot create regular file '…/workspace/CLAWBOX.md': Permission denied
  WARNING: could not seed CLAWBOX.md in the OpenClaw workspace
[exit=0]                  ← install's own cause is kept on stderr; the gateway starts
```

GREEN, at the final head:

```
 Test Files  2 passed (2)
      Tests  24 passed (24)          ← 0 skipped; the mode-based cases run as non-root
```

Neighbouring suites (all 15 `gateway-pre-start-*`, the guide test, plus `hermes-shell-scan`,
`system-profile-scripts`, `skill-install-no-restart`):

```
 Test Files  18 passed (18)
      Tests  310 passed (310)
```

Whole unit project after the rebase: **547 files, 8630 tests, all passing**.
`npx tsc --noEmit` exits 0. `bash -n scripts/gateway-pre-start.sh` clean.

The rewritten awk was exercised against **mawk 1.3.4**, the same implementation the box uses
(`/usr/bin/awk → /etc/alternatives/awk → mawk` on Ubuntu): CRLF template (one heading, next section
not dragged in, trailing `---\r` trimmed), a workspace path with spaces and non-ASCII (all three
writes land, both markers exactly once), a renamed heading (warns, appends nothing), and idempotence
over repeated runs.

### Three bug classes, self-checked on this diff

- *Probe-once*: none introduced — `-r`, `-f` and both `grep -qF` guards are evaluated on every
  gateway start, nothing is cached across the process lifetime.
- *False success*: the seed now prints "Seeded CLAWBOX.md" only inside the `then` branch of the
  `install` it describes; no `|| true` was added, and the extraction still captures awk's exit status
  rather than its output alone. The trim cannot empty a found section (the heading line is never
  blank and never `---`), so the "heading renamed" warning still means what it says.
- *False failure*: the new warnings fire only on a genuinely non-zero write or an unreadable
  template; `install` does not return non-zero after writing.

## Device leg

**Unproven on hardware.** Every proof above is a temp-dir reproduction against the shipped `.sh`, a
static read of the source, or a mawk run on the dev PC. **Nothing has run on a box**, and this PR
touches no device. Verbatim, the five items the review names:

1. The block executing inside the **real 2424-line `gateway-pre-start.sh`** under the real systemd
   unit — the tests run a 7 KB slice in a stub shell with only `CLAWBOX_ROOT` and `CLAWBOX_WORKSPACE`
   set. An `ExecStartPre` exit code on a box has not been observed.
2. The append landing on the box's **actual** `~/.openclaw/workspace/AGENTS.md` and `CLAWBOX.md`
   (owner, mode, the real drift), and the gateway coming back up after it.
3. That OpenClaw **re-reads** the grown `AGENTS.md` into the next session — the file map says it
   does; that has not been observed live at this head.
4. That the behaviour actually changes: re-running the TASK-612 prompt ("restart the gateway") on the
   box and seeing the owner's path in the answer instead of a parked `operator_approval`. That is the
   only test of the deliverable.
5. A workspace resolved from a non-default `agents.defaults.workspace`
   (`gateway-pre-start.sh:2288–2303`).

After merge: deploy beta head to the box, restart the gateway once, diff `AGENTS.md` and `CLAWBOX.md`
before/after, and re-run the incident prompt.

---

## Round 3 — a second Opus pass on the round-2 head: `APPROVE-WITH-NITS`

0 High, 4 Medium, 5 Low. It re-verified both round-2 blockers by execution (not by reading),
confirmed the diff is exactly the 4 intended files, and confirmed none of the new assertions is
vacuous — all six fail on `5017bc85`. Three of its findings were against my own round-2 work and are
applied here.

### M1 (applied) — the copy that actually reaches the model had no test

The rule in `AGENTS.md` is the delivery path; `CLAWBOX.md` is the long form the agent may never open.
The guide's text was pinned hard, and the `printf` body that writes `AGENTS.md` was pinned only by its
heading. Demonstrated: regressing that body back to `Settings -> AI` and *"Their own control is
Settings -> System"* left **all 23 tests green**. Had round 2 fixed only the `.md`, CI would have been
green and the box would still have shipped the round-1 defect — false success in the test layer.

The screens the rule names are now asserted on the appended `AGENTS.md` itself. Confirmed by mutation:
that exact regression now fails.

### M3 (applied) — a *missing* template silently withheld the rule

The `-r` move put readability inside the chain so the AGENTS.md rule survives an **unreadable**
template. But the block was still wrapped in `[ -f "$CLAWBOX_GUIDE_SRC" ]`, so an **absent** template
skipped everything with exit 0 and **no output at all** — while the new comment claimed the rule needs
no template. The same shape as the round-1 H2 comment: an invariant that was three-quarters true, and
the quarter that failed silently withheld the deliverable.

Fixed in one line rather than by narrowing the claim: the enclosing test is now
`[ -d "$CLAWBOX_WORKSPACE" ]`, and the `-r` check inside the chain covers missing and unreadable
alike — so the fault is *reported* instead of passed over, and the rule still lands. Pinned by a test.

### M4 (applied — a finding against an edit I had not yet committed)

I had loosened the structural guard test to exempt `… || true`. That was wrong: it would admit

```bash
install -m 644 "$CLAWBOX_GUIDE_SRC" "$CLAWBOX_GUIDE_DST" || true
echo "  Seeded CLAWBOX.md in OpenClaw workspace"
```

— which boots fine and prints the success line over a failed seed. That is the false-success class
this block exists to remove, and strictly worse than the bug the test was written to catch. The
exemption is dropped; the mutation above now fails the suite.

### L1 (applied) — the guard test covered only copy verbs

The three `printf … >> file` appends were invisible to it, and on root (where both mode-based cases
skip) nothing covered them. The filter now counts every write — copy verbs and append redirections —
and requires each to sit in a condition (`if …` / `elif …` / `…; } >> f; then`). It also asserts it
found at least the block's four writes, so an empty result cannot pass vacuously. Verified by
re-baring the pointer append: caught.

### L2 (applied in part, refuted in part)

The **awk** bound was a prefix test, so a future `## System actions and restarts (advanced)` would
have opened the extraction and never closed it, swallowing every following section. It now matches the
heading as a whole line (CR-tolerant). Reproduced before and after: that heading now warns
*"the shipped guide no longer carries …"* and appends nothing, instead of silently swallowing the file.

The **`grep -qF`** destination markers are deliberately left as substring tests. Making them
whole-line (`-qxF`) would re-append the whole section on every boot for any owner who saved
`CLAWBOX.md` or `AGENTS.md` with CRLF line endings — trading a theoretical false negative for a
repeating real one.

### Deferred, with reasons

- **M2 / round-1 L2 — a partial write permanently truncates the section (filed as TASK-707).**
  The round-3 pass produced a faithful ENOSPC-shaped reproduction that defeats my round-2 refutation:
  the heading is written first, so a fragment satisfies the `grep -qF` marker, every later boot appends
  nothing, and the file stays cut mid-sentence — losing precisely the *"Never queue an
  `operator_approval`"* paragraph. Boot safety holds (exit 0, warned once at boot), but the loss is
  permanent and silent thereafter. **Not fixed here on purpose:** every candidate (atomic
  temp-file+rename, or a size-rollback on the failure branch) adds new logic to the one script whose
  failure takes the gateway down, and **this PR has no device leg** to validate a boot-path
  restructure. Shipping that unvalidated is a worse risk than the ENOSPC path it closes. Filed with the
  reproduction and both candidate fixes.
- **L5 — `install` replaces a dangling symlinked `CLAWBOX.md`.** Acknowledged, not fixed. GNU `install`
  unlinks and recreates its target, so an owner who symlinked the guide into a not-yet-mounted folder
  loses the link. Very low probability; noted because the comment invites operators to delete the file
  to re-seed.
- **L3 / L4** — round-1 M2 and L6, already recorded above as **TASK-706**.

### One correction to the round-1 review, for the record

Round 1 proposed covering H2 with "an unwritable workspace directory, which fails for root too, so it
needs no `skipIf`". That is not true: **root bypasses directory mode bits**, and GNU `install` unlinks
and recreates its destination, so neither a read-only destination nor a dangling symlink fails for root
either (both were tried — the symlink case printed "Seeded CLAWBOX.md" and exited 0). No
permission-based case here is uid-independent. The `0555` case therefore keeps a `skipIf`, matching the
file's two existing ones, and the root-container hole is closed by the structural test instead. Round 3
confirmed the split and agreed CI runs non-root, so all mode-based cases execute there.

### CODE REVIEW

File: src/tests/unit/clawbox-workspace-guide.test.ts [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+ *
+ * TASK-612: asked "restart the gateway", the agent reached for OpenClaw's
+ * operator-approval path — the native `approval.request` RPC behind the
+ * `operator.approvals` scope, which is the right mechanism on a box whose
+ * operator surface renders it. ClawBox's chat renders nothing of the kind
+ * today, so the proposal sat unanswered until the run ended or a gateway
+ * restart cancelled it (`operator_approval_cancelled_gateway_restart`), and
+ * the owner was told the restart was waiting for an approval they had nowhere
+ * to give. Until that card exists (follow-up under TASK-604), the guide has to
+ * name the owner's real path — Settings -> System — and forbid the queue.
```
[the remark this answers is not in the document]
Comment (KrasimirKralev) [reply src/tests/unit/clawbox-workspace-guide.test.ts]: Both parts taken — thanks, this was right on both counts.

**Stale docstring.** Reworded. It now reads "…the guide has to forbid the queue and name the owner's real path — the power menu in the desktop tray, NOT Settings -> System, which carries no power control at all." The test title at line 53 was carrying the same reversed sense and is reworded too ("gives the owner's control as the tray power menu, and Settings -> System only for what is on it"), so neither teaches the defect the PR removes.

**Follow-up id.** You are right that it is TASK-704, not TASK-604. TASK-704 (render a pending approval as an approve/deny card on OpenClaw's `approval.request` RPC) sits *under* TASK-604, so the docstring now names both: `(TASK-704, under TASK-604)`.

While in that file, a related defect the same class of check turned up — the guide sent the owner to **Settings → About** for the hostname. The editable device name is the "Local URL" card at `SettingsApp.tsx:3425`, inside `activeSection === "wifi"`, whose nav label is `settings.network` → **Network**; grepping the About section (`:5638`–`:5800`) for `hostname|rename|deviceName` returns nothing. Corrected, and pinned by a test that fails if any clause naming the device name stops naming Network or starts naming About. Same for "Settings → AI", which is a tab labelled **Providers** (`labelKey: "settings.providers"`).

Two more from the review pass, both in this push: the `install -m 644` seed was still bare under `set -euo pipefail` (with `ExecStartPre=` carrying no leading `-`, an unwritable workspace took the gateway down over an advisory text file), and the `AGENTS.md` rule text — the copy the harness actually injects — had no test pinning it, so it could be regressed while the suite stayed green. Both fixed and covered.

File: scripts/gateway-pre-start.sh [hunk 2]
```diff
@@ -2312,25 +2314,162 @@ fi
...
+    if install -m 644 "$CLAWBOX_GUIDE_SRC" "$CLAWBOX_GUIDE_DST"; then
+      echo "  Seeded CLAWBOX.md in OpenClaw workspace"
+    else
+      # The first-boot and post-factory-reset path, and the one write in this
+      # block that used to be bare: a full rootfs, a filesystem remounted
+      # read-only after errors, or the documented "delete CLAWBOX.md to
+      # re-seed" step on such a box all land here.
+      echo "  WARNING: could not seed CLAWBOX.md in the OpenClaw workspace" >&2
+    fi
+  elif ! grep -qF "$CLAWBOX_GUIDE_TOPUP" "$CLAWBOX_GUIDE_DST"; then
```
[the remark this answers is not in the document]
Comment (KrasimirKralev) [reply scripts/gateway-pre-start.sh:2356]: Verified and declined — the premise is right, the remedy is not. `grep -qxF` (whole-line) misses a heading that carries a CR (CRLF templates and files edited on Windows exist on field boxes): measured with GNU grep 3.11, the marker then reads "absent" and the section is re-appended on every boot, forever. The obvious CR-tolerant form `\r?$` in an ERE matches a literal `r`, so it fails too. Substring matching stays deliberately; the risk it carries (a longer heading containing the marker text) is recorded as a low in the review and needs a proper CR-aware match in its own change, not a one-word flag.

File: src/tests/unit/clawbox-workspace-guide.test.ts [hunk 3]
```diff
@@ -0,0 +1,111 @@
...
+  it("separates the gateway restart it refuses from the device restart it owns", () => {
+    const section = systemActionsSection();
+    // The gateway restart, by name and with a reason the agent can act on.
+    expect(section.toLowerCase()).toContain("gateway");
+    expect(section).toMatch(/not yours|is not yours to do/i);
+    // And the capability the device actually ships, which an earlier draft of
+    // this section denied outright ("you have no tool for any of them") — the
+    // guide would then have talked a confirm-gated, owner-consented tool out
+    // of existence. mcp/tools/system.ts registers it on both editions.
+    expect(section).toContain("system_power");
```
[the remark this answers is not in the document]
Comment (KrasimirKralev) [reply src/tests/unit/clawbox-workspace-guide.test.ts:51]: Valid nit, taken as a follow-up rather than folded in here: the guide wraps `openclaw approvals resolve` across two lines, so a `toContain` pin would fail — it needs `/openclaw approvals\s+resolve/`. Changing the tests now would invalidate the final review on this head; recorded on TASK-612 as the next small change to the guide tests.
